version: "3"

services:
  nginx:
    container_name: nginx
    depends_on:
      - wordpress
    build: ./requirements/nginx/
    volumes:
      - wp_volume:/var/www/html/
    restart: always
    networks:
      - bridge-network
    env_file:
      - .env
    ports:
      - "443:443"

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/
    volumes:
      - /home/adel/42/Inception/srcs/requirements/data/mariadb:/var/lib/mysql
    networks:
      - bridge-network
    env_file:
      - .env
    restart: always

  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    build: ./requirements/wordpress/
    volumes:
      - /home/adel/data/wordpress:/var/www/html/
    restart: always
    networks:
      - bridge-network
    env_file:
      - .env
    
volumes:
  wp_volume:
    driver: local
    driver_opts:
      device: /home/adel/data/wordpress
      o: bind
      type: none
  db_volume:
    driver: local
    driver_opts:
      device: /home/adel/42/Inception/srcs/requirements/data/mariadb
      o: bind
      type: none

networks:
  bridge-network:
    driver: bridge