version: "3.3"

services:
  nginx:
    container_name: nginx
    depends_on:
      - wordpress
    build: ./requirements/nginx/
    volumes:
      - wp_volume:/var/www/html/
      - ./nginx_logs:/var/log/nginx  
    restart: always
    networks:
      - bridge-network
    env_file:
      - .env
    ports:
      - "443:443"

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb/
    volumes:
      - db_volume:/var/lib/mysql
    networks:
      - bridge-network
    env_file:
      - .env
    restart: always

  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
      - redis
    build: ./requirements/wordpress/
    volumes:
      - wp_volume:/var/www/html/
      - ./static:/usr/share/nginx/html
    restart: always
    networks:
      - bridge-network
    env_file:
      - .env

  redis:
    container_name: redis
    build: ./requirements/bonus/redis/
    volumes:
      - redis_volume:/data
    restart: always
    networks:
      - bridge-network
    env_file:
      - .env

  ftp:
    container_name: ftp
    build: ./requirements/bonus/ftp/
    ports:
      - "21:21"
      - "21100-21110:21100-21110"
    volumes:
      - wp_volume:/var/www/html"
    restart: always
    networks:
      - bridge-network
    env_file:
      - .env

  adminer:
    container_name: adminer
    build: ./requirements/bonus/adminer/
    ports:
      - "9000:9000"
    restart: always
    networks:
      - bridge-network
    volumes:
      - adminer_volume:/data

  fail2ban:
    build: ./requirements/bonus/fail2ban/
    container_name: fail2ban
    restart: unless-stopped
    cap_add:
      - NET_ADMIN  # Allow Fail2Ban to modify firewall rules
    networks:
      - bridge-network  # Use the same network as other services
    volumes:
      - ./logs/nginx:/var/log/nginx
      - ./logs/mariadb:/var/log/mysql
      - ./logs/redis:/var/log/redis
      - ./logs/ftp:/var/log/ftp
      - /var/log/auth.log:/var/log/auth.log  # Host SSH logs
    env_file:
      - .env
  website:
    container_name: website
    build: ./requirements/bonus/website/
    restart: always
    networks:
      - bridge-network
    depends_on:
      - nginx
    ports:
      - "1111:1111"

volumes:
  wp_volume:
    driver: local
    driver_opts:
      device: /home/$USER/data/wordpress
      o: bind
      type: none
  db_volume:
    driver: local
    driver_opts:
      device: /home/$USER/data/mariadb
      o: bind
      type: none
  adminer_volume:
    driver: local
    driver_opts:
      device: /home/$USER/data/mariadb
      o: bind
      type: none
  redis_volume:
    driver: local
    driver_opts:
      device: /home/$USER/data/mariadb
      o: bind
      type: none

networks:
  bridge-network:
    driver: bridge
